#!/bin/bash

unset KILOMETRIKISA_DB
unset KILOMETRIKISA_DBUSER
unset KILOMETRIKISA_DBPASSWORD
unset KILOMETRIKISA_DBHOST 

echo "Enter KILOMETRIKISA_DB: "
read KILOMETRIKISA_DB

echo "Enter KILOMETRIKISA_DBUSER: "
read KILOMETRIKISA_DBUSER

echo "Enter KILOMETRIKISA_DBPASSWORD: "
read KILOMETRIKISA_DBPASSWORD

echo "Enter KILOMETRIKISA_DBHOST: "
read KILOMETRIKISA_DBHOST

export KILOMETRIKISA_DB="${KILOMETRIKISA_DB}"
export KILOMETRIKISA_DBUSER="${KILOMETRIKISA_DBUSER}"
export KILOMETRIKISA_DBPASSWORD="${KILOMETRIKISA_DBPASSWORD}"
export KILOMETRIKISA_DBHOST="${KILOMETRIKISA_DBHOST}"
