#!/bin/bash

unset KILOMETRIKISA_DB
unset KILOMETRIKISA_DBUSER
unset KILOMETRIKISA_DBPASSWORD
unset KILOMETRIKISA_DBHOST 

echo "Enter KILOMETRIKISA_DB: "
read KILOMETRIKISA_DB

echo "Enter KILOMETRIKISA_DBUSER: "
read KILOMETRIKISA_DBUSER

echo "Enter KILOMETRIKISA_DBPASSWORD: "
read KILOMETRIKISA_DBPASSWORD

echo "Enter KILOMETRIKISA_DBHOST: "
read KILOMETRIKISA_DBHOST

echo "Enter STRAVA_ACCESS_TOKEN: "
read STRAVA_ACCESS_TOKEN

echo "Enter STRAVA_CLIENT_ID: "
read STRAVA_CLIENT_ID

echo "Enter STRAVA_CLIENT_SECRET: "
read STRAVA_CLIENT_SECRET

echo "Enter STRAVA_REDIRECT_URI: "
read STRAVA_REDIRECT_URI

export KILOMETRIKISA_DB="${KILOMETRIKISA_DB}"
export KILOMETRIKISA_DBUSER="${KILOMETRIKISA_DBUSER}"
export KILOMETRIKISA_DBPASSWORD="${KILOMETRIKISA_DBPASSWORD}"
export KILOMETRIKISA_DBHOST="${KILOMETRIKISA_DBHOST}"
export STRAVA_ACCESS_TOKEN="${STRAVA_ACCESS_TOKEN}"
export STRAVA_CLIENT_ID="${STRAVA_CLIENT_ID}"
export STRAVA_CLIENT_SECRET="${STRAVA_CLIENT_SECRET}"
export STRAVA_REDIRECT_URI="${STRAVA_REDIRECT_URI}"